name: Pylint

on:
  push:
    branches: ["pylint-automation"]
  pull_request:
    branches: ["pylint-automation"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pytest
          pip install -r ./pipeline_games/requirements.txt
          pip install -r ./pipeline_reviews/requirements.txt
          pip install -r ./dashboard/requirements.txt
          pip install -r ./report/requirements.txt
      - name: Analysing push files with pylint
        run: |
          pylint --fail-under=5 ./pipeline_reviews/*.py
