name: Pytest
on:
  push:
    branches:
      - main
    paths:
      - "pipeline_games/**"
      - "pipeline_reviews/**"
jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install and upgrade pytest
      run: python -m pip install --upgrade pytest

    - name: Install requirements pipeline_reviews
      run: python -m pip install -r pipeline_reviews/requirements.txt

    - name: Install requirements pipeline_games
      run: python -m pip install -r pipeline_games/requirements.txt

    - name: Download nltk additions
      run: python pipeline_reviews/nltk_download.py

    - name: Run pytest on pipeline_games
      run: pytest pipeline_games/
    - name: Run pytest on pipeline_reviews
      run: pytest pipeline_reviews/
